# Product Service Configuration
spring.application.name=product-service
server.port=8081
# Port on which the Product Service runs

## Eureka Client Configuration
#eureka.client.enabled=false
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.client.service-url.default-zone=http://localhost:8761/eureka
## Eureka server URL

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate auto configuration for database schema management
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Show SQL queries in the console for debugging

# Format SQL queries
spring.jpa.properties.hibernate.format_sql=true

#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.enabled=false
#

#spring.security.user.name=admin
#spring.security.user.password=admin123